# Generated by Django 3.1.6 on 2022-05-14 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19, null=True)),
                ('group', models.CharField(choices=[('CIVIL', 'CIVIL'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('CSC', 'CSC')], max_length=15)),
                ('subject', models.CharField(choices=[('english', 'english'), ('m1', 'm1'), ('history', 'history'), ('civics', 'civics'), ('computers', 'computers'), ('literature', 'literature')], max_length=20)),
                ('mobile', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('country', models.CharField(choices=[('AUSTRALIA', 'AUSTRALIA'), ('BANGLADESH', 'BANGLADESH'), ('CHINA', 'CHINA'), ('DENMARK', 'DENMARK'), ('EGYPT', 'EGYPT'), ('INDIA', 'INDIA'), ('SWEDEN', 'SWEDEN'), ('USA', 'USA')], max_length=15)),
                ('marks_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
